name: Build and deploy to ICF

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - 'img/*'
      - .github/workflows/codeql-analysis.yml

jobs:
  build-and-deploy:
    env:
      GPR_USER: mattwelke
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '16'
    - uses: gradle/wrapper-validation-action@v1
    - name: Install IBM Cloud CLI
      run: |
        curl -sL https://raw.githubusercontent.com/IBM-Cloud/ibm-cloud-developer-tools/master/linux-installer/idt-installer | bash
    - name: Build and deploy title fetcher action
      env:
        # Only present for masking in GHA logs
        IBM_CLOUD_SERVICE_ID: ${{ secrets.IBM_CLOUD_SERVICE_ID }}
        IBM_CLOUD_ACCOUNT_ID: ${{ secrets.IBM_CLOUD_ACCOUNT_ID }}
      run: |
        ./scripts/build_and_deploy_title_fetcher.sh \
          ${{ secrets.DEPLOY_API_KEY }}
    - name: Build and deploy GCP data sharer action
      env:
        # Only present for masking in GHA logs
        IBM_CLOUD_SERVICE_ID: ${{ secrets.IBM_CLOUD_SERVICE_ID }}
        IBM_CLOUD_ACCOUNT_ID: ${{ secrets.IBM_CLOUD_ACCOUNT_ID }}
      run: |
        ./scripts/build_and_deploy_gcp_data_sharer.sh \
          ${{ secrets.DEPLOY_API_KEY }} \
          ${{ secrets.GCP_CREDS_BASE_64 }}
