name: Run tests

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - 'img/*'
      - .github/workflows/codeql-analysis.yml

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - uses: gradle/wrapper-validation-action@v1
    - name: Run tests
      run: ./gradlew -Pgpr.user=mattwelke -Pgpr.key=${{ secrets.GPR_TOKEN }} test
